version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: integration_tests_postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: integration_tests_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - integration_tests_network

  redis:
    image: redis:latest
    container_name: integration_tests_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass '' --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - integration_tests_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: integration_tests_pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - integration_tests_network

volumes:
  redis_data:
  postgres_data:

networks:
  integration_tests_network:
    driver: bridge
